export const LOAD_INITIAL_TREE = 'LOAD_INITIAL_TREE';
export const UPDATE_SELECTED_TREE = 'UPDATE_SELECTED_TREE';
// export const FETCH_TREE_FAILED = 'FETCH_TREE_FAILED';
// export const LOAD_DROPPED_TREE = 'LOAD_DROPPED_TREE';
// export const EDIT_NODE = 'EDIT_NODE';
// export const SET_ROUTE_PARAMS = 'SET_ROUTE_PARAMS';
// export const UPDATE_KEYVALPAIR_ARRAY='UPDATE_KEYVALPAIR_ARRAY';
// export const TREE_REF_ARRAY='TREE_REF_ARRAY';